document.write('		<!-- START MENU BAR -->');
document.write('		<!-- START MENU BAR -->');
document.write('		<!-- START MENU BAR -->');
document.write('		<!-- START MENU BAR -->');
document.write('		<TABLE CELLPADDING="0" CELLSPACING="0" border="0" class="ContentTable">');
document.write('			<TR>');
document.write('				<TD VALIGN="MIDDLE" Align="center" height="52">');
document.write('						<B>');
document.write('							<A HREF="#" class="menu">PAC</A>&nbsp;|&nbsp;');
document.write('							<A HREF="#" class="menu">CATALOG</A>&nbsp;|&nbsp;');
document.write('							<A HREF="#" class="menu">REPORTS</A>&nbsp;|&nbsp;');
document.write('							<A HREF="#" class="menu">IMPORT/EXPORT</A>&nbsp;|&nbsp;');
document.write('							<A HREF="#" class="menu">ADMINISTRATION</A>&nbsp;|&nbsp;');
document.write('							<A HREF="#" class="menu">OPERATOR</A>');
document.write('						</B>')
document.write('				</TD>');
document.write('			</TR>');
document.write('		</TABLE>');
document.write('		<!-- END MENU BAR -->');
document.write('		<!-- END MENU BAR -->');
document.write('		<!-- END MENU BAR -->');
document.write('		<!-- END MENU BAR -->');