
                <tr>
                    <td class="ContentHeaderTD">Attention</td>
                    <td class="ContentTD" COLSPAN="5">&nbsp;</td>
                </tr>
                <tr>
                    <td class="ContentHeaderTD">Address 1</td>
                    <td class="ContentTD">&nbsp;</td>
                    <td class="ContentHeaderTD">Address 2</td>
                    <td class="ContentTD" colspan="3">&nbsp;</td>
                </tr>
                <tr>
                    <td class="ContentHeaderTD" width="11%">City</td>
                    <td class="ContentTD" width="34%">&nbsp;</td>
                    <td class="ContentHeaderTD" width="14%">State</td>
                    <td class="ContentTD" width="18%">&nbsp;</td>
                    <td class="ContentHeaderTD" width="10%">Zip/Postal Code</td>
                    <td class="ContentTD" width="13%">&nbsp;</td>
                </tr>
                <tr>
                    <td class="ContentHeaderTD">County</td>
                    <td class="ContentTD">&nbsp;</td>
                    <td class="ContentHeaderTD">Province</td>
                    <td class="ContentTD">&nbsp;</td>
                    <td class="ContentHeaderTD">Country</td>
                    <td class="ContentTD">&nbsp;</td>
                </tr>
                <tr>
                    <td class="ContentHeaderTD">Bad Address</td>
                    <td class="ContentTD"><input name="addressBadFlag" type="checkbox" disabled></td>
                    <td class="ContentHeaderTD">Date Marked Bad</td>
                    <td class="ContentTD" colspan="3">&nbsp;</td>
                </tr>

<%if (title.startsWith("Organization Associate Detail")) { %>
<!-- Additions for Organization Associate Detail -->
                <tr>
                    <td class="ContentHeaderTD">Last Updated</td>
                    <td class="ContentTD">&nbsp;</td>
                    <td class="ContentHeaderTD">Updated By</td>
                    <td class="ContentTD" colspan="3">&nbsp;</td>
                </tr>
<% } %>
