<!-- Begin


document.write('The Member Tabs are located at the top area and again at the bottom area ');
document.write('of the Member Detail screen.  The tab appears as rectangles with embedded ');
document.write('words.  The embedded words represent actions, which either cause a different ');
document.write('page to display or cause the Enterprise Application to perform some ');
document.write('action.  A tab action is active if the <U>word(s) in the tab are underlined ');
document.write('and selectable</U>.  Note that if the action displays a particular screen,  ');
document.write('it is typically not active when that screen is being displayed.<BR/><BR/>');
document.write(' ');
document.write('The <U><I>Edit</I></U> tab action is different. It displays the Edit version ');
document.write('of the current displayed screen.  If the screen has an Edit version. For ');
document.write('example, if the current screen being displayed is General Demographic, ');
document.write('then selection of the Edit action will display the General Demographic ');
document.write('Information - Edit screen. <U>NOTE:</U> Some screens, such as the  ');
document.write('Mailing Lists Information and Correspondence History screen, do not ');
document.write('have a corresponding Edit screen.<BR/><BR/>');
document.write(' ');
document.write(' ');
document.write('<U>The number of actions available to the user in the Member Tab depends on the ');
document.write('privileges a user has been granted</U>.  Therefore, not all of the actions listed ');
document.write('below may be available.  In addition, there are a few actions that are ');
document.write('placeholders for future releases, even if they are visible, these actions will ');
document.write('always be inactive.<BR/><BR/>  ');
document.write(' ');
document.write('The following is a list of the <U><I>Member Tab actions</I></U>:<BR/> ');
document.write(' ');
document.write('<TABLE class="DataFONT" align="center" width="95%"> ');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Member Detail (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the Member Detail screen</TD>  ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Edit (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the Edit version of the current screen, if applicable</TD>');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>General Demographic (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the General Demographic Information screen</TD>  ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Political/Legislative (link)</U></B></TD>  ');
document.write('  <TD width="51%">Displays the Political/LegislativeInformation screen</TD> ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Mailing Lists (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the Mailing Lists Information screen</TD>  ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Participation (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the Participation Information screen</TD>  ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Political Rebate (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the Political Rebate Information screen</TD>  ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Correspondence History (link)</U></B></TD> ');
document.write('  <TD width="51%">Displays the Correspondence History Information screen</TD>  ');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Maintain Pending Reports (link)</U></B></TD>  ');
document.write('  <TD width="51%">Placeholder for future release functionality</TD>');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>PAC (link)</U></B></TD>  ');
document.write('  <TD width="51%">Placeholder for future release functionality</TD>');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Organizing Details (link)</U></B></TD>  ');
document.write('  <TD width="51%">Placeholder for future release functionality</TD>');
document.write('  </TR>');
document.write('  <TR valign="top">');
document.write('  <TD width="34%"><B><U>Search Results (link)</U></B></TD>');
document.write('  <TD width="51%">Displays the current Affiliate Search Results screen if there are current search results</TD> ');  
document.write('  </TR>');
document.write('</TABLE>  ');

// End -->